/* ============================================================
   Photo gallery — Start.png … by date … last.png

   Order comes from data/photo-gallery.json, generated by
   tools/build-photo-gallery.mjs. Add a photo to the folder,
   re-run that script, done.

   Transitions are a true crossfade: two stacked layers swap
   opacity, so a slide never flashes empty between photos.
   ============================================================ */

(() => {
  'use strict';

  const host = document.getElementById('photo-gallery');
  if (!host) return;

  const reduced = window.matchMedia('(prefers-reduced-motion: reduce)').matches;

  let items = [];
  let idx = 0;
  let front = 0;        // which of the two layers is currently visible
  let layers = [];
  let busy = false;
  let timer = null;

  const t = (k, fb) => (window.MASite ? window.MASite.t(k) : '') || fb;

  /* ── Build once ─────────────────────────────────────────── */
  function mount() {
    host.replaceChildren();

    const stage = el('div', 'pg');

    const frame = el('div', 'pg__frame');
    layers = [el('div', 'pg__layer is-front'), el('div', 'pg__layer')];
    layers.forEach((l) => {
      const img = el('img', 'pg__img');
      img.decoding = 'async';
      l.appendChild(img);
      frame.appendChild(l);
    });

    const prev = navBtn('prev', 'M15 5l-7 7 7 7', t('gallery.prev', 'Previous photo'));
    const next = navBtn('next', 'M9 5l7 7-7 7', t('gallery.next', 'Next photo'));
    frame.append(prev, next);

    // Filenames are not titles — no caption text, just the position.
    const cap = el('div', 'pg__cap');
    const count = el('p', 'pg__count mono');
    cap.append(count);

    const dots = el('div', 'pg__dots');
    dots.setAttribute('role', 'tablist');
    dots.setAttribute('aria-label', 'Photos');

    stage.append(frame, cap, dots);
    host.appendChild(stage);

    host._refs = { count, dots, prev, next, frame };

    prev.addEventListener('click', () => go(idx - 1));
    next.addEventListener('click', () => go(idx + 1));

    buildDots();
    wireGestures(frame);
    show(0, true);
  }

  function el(tag, cls) {
    const n = document.createElement(tag);
    if (cls) n.className = cls;
    return n;
  }

  function navBtn(dir, path, label) {
    const b = el('button', `pg__nav pg__nav--${dir}`);
    b.type = 'button';
    b.setAttribute('aria-label', label);
    b.innerHTML =
      `<svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor"
            stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
         <path d="${path}"/></svg>`;
    return b;
  }

  function buildDots() {
    const { dots } = host._refs;
    dots.replaceChildren();
    // Too many dots becomes noise; past ~14 photos show a progress bar instead.
    if (items.length > 14) {
      dots.classList.add('pg__dots--bar');
      const bar = el('span', 'pg__bar');
      const fill = el('span', 'pg__bar-fill');
      bar.appendChild(fill);
      dots.appendChild(bar);
      return;
    }
    dots.classList.remove('pg__dots--bar');
    items.forEach((_, i) => {
      const d = el('button', 'pg__dot');
      d.type = 'button';
      d.setAttribute('role', 'tab');
      d.setAttribute('aria-label', `Photo ${i + 1}`);
      d.addEventListener('click', () => go(i));
      dots.appendChild(d);
    });
  }

  /* ── Crossfade ──────────────────────────────────────────── */
  function show(i, immediate = false) {
    const item = items[i];
    if (!item) return;

    const incoming = layers[1 - front];
    const outgoing = layers[front];
    const img = incoming.querySelector('img');

    // A cached image fires BOTH `complete` and `onload`, so this must run
    // at most once — swapping twice flips the layers back and wedges the
    // gallery on whichever photo was showing.
    let swapped = false;
    const swap = () => {
      if (swapped) return;
      swapped = true;
      clearTimeout(guard);
      incoming.classList.add('is-front');
      outgoing.classList.remove('is-front');
      front = 1 - front;
      busy = false;
    };

    img.alt = item.alt || '';

    if (immediate) {
      img.src = item.src;
      const back = outgoing.querySelector('img');
      back.src = item.src;
      back.alt = item.alt || '';
      busy = false;
      return void afterShow(i);
    }

    busy = true;
    // Never let a slow or dead image lock navigation.
    const guard = setTimeout(swap, 2500);

    // Swap as soon as the image is decoded. Deliberately NOT inside
    // requestAnimationFrame: rAF is paused in background tabs, which would
    // leave the gallery frozen until a visitor returns to it. The incoming
    // layer is already at opacity 0, so the CSS transition runs correctly
    // from a plain class change.
    img.onload = swap;
    img.onerror = swap;
    img.src = item.src;
    // Cached images may already be decoded and fire no load event.
    if (img.complete && img.naturalWidth) swap();

    afterShow(i);
  }

  function afterShow(i) {
    syncMeta(i);
    preload(i);
  }

  function syncMeta(i) {
    const { count, dots } = host._refs;
    count.textContent = `${i + 1} / ${items.length}`;

    if (dots.classList.contains('pg__dots--bar')) {
      const fill = dots.querySelector('.pg__bar-fill');
      if (fill) fill.style.transform = `scaleX(${(i + 1) / items.length})`;
      return;
    }
    [...dots.children].forEach((d, n) => {
      const on = n === i;
      d.classList.toggle('is-on', on);
      d.setAttribute('aria-selected', String(on));
    });
  }

  /** Keep the neighbours warm so next/prev is instant. */
  function preload(i) {
    [i + 1, i - 1].forEach((n) => {
      const it = items[(n + items.length) % items.length];
      if (it) { const p = new Image(); p.src = it.src; }
    });
  }

  function go(i) {
    if (busy || !items.length) return;
    idx = ((i % items.length) + items.length) % items.length;
    show(idx);
  }

  /* ── Gestures & keyboard ────────────────────────────────── */
  function wireGestures(frame) {
    let x0 = null, y0 = null;
    frame.addEventListener('touchstart', (e) => {
      x0 = e.touches[0].clientX; y0 = e.touches[0].clientY;
    }, { passive: true });
    frame.addEventListener('touchend', (e) => {
      if (x0 === null) return;
      const dx = e.changedTouches[0].clientX - x0;
      const dy = e.changedTouches[0].clientY - y0;
      if (Math.abs(dx) > 50 && Math.abs(dx) > Math.abs(dy) * 1.5) go(idx + (dx < 0 ? 1 : -1));
      x0 = y0 = null;
    }, { passive: true });

    // Arrow keys only while the gallery is on screen and focused within.
    frame.tabIndex = 0;
    frame.addEventListener('keydown', (e) => {
      if (e.key === 'ArrowRight') { e.preventDefault(); go(idx + 1); }
      else if (e.key === 'ArrowLeft') { e.preventDefault(); go(idx - 1); }
    });
  }

  /* ── Load ───────────────────────────────────────────────── */
  async function load() {
    try {
      const res = await fetch('data/photo-gallery.json', { cache: 'no-cache' });
      if (!res.ok) throw new Error('no gallery data');
      const data = await res.json();
      items = Array.isArray(data.images) ? data.images : [];
      if (!items.length) throw new Error('empty');
      mount();
    } catch (_) {
      const p = document.createElement('p');
      p.className = 'lead';
      p.textContent = t('gallery.empty', 'The gallery is empty right now.');
      host.replaceChildren(p);
    }
    clearInterval(timer);
  }

  document.addEventListener('site:lang', () => { if (items.length) syncMeta(idx); });

  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', load);
  else load();
})();
