/* ============================================================
   Photo gallery — Start.png … by date … last.png

   Order comes from data/photo-gallery.json, generated by
   tools/build-photo-gallery.mjs. Add a photo to the folder,
   re-run that script, done.

   Transitions are a true crossfade: two stacked layers swap
   opacity, so a slide never flashes empty between photos.
   ============================================================ */

(() => {
  'use strict';

  const host = document.getElementById('photo-gallery');
  if (!host) return;

  const reduced = window.matchMedia('(prefers-reduced-motion: reduce)').matches;

  let items = [];
  let idx = 0;
  let front = 0;        // which of the two layers is currently visible
  let layers = [];
  let busy = false;
  let timer = null;

  const t = (k, fb) => (window.MASite ? window.MASite.t(k) : '') || fb;

  /* ── Build once ─────────────────────────────────────────── */
  function mount() {
    host.replaceChildren();

    const stage = el('div', 'pg');

    const frame = el('div', 'pg__frame');
    layers = [el('div', 'pg__layer is-front'), el('div', 'pg__layer')];
    layers.forEach((l) => {
      const img = el('img', 'pg__img');
      img.decoding = 'async';
      l.appendChild(img);
      frame.appendChild(l);
    });

    // The arrows stand at the two sides of the plate, so the photo is never
    // scrolled out of view to move on. Keys work too (see onKey).
    const prev = navBtn('prev', 'M15 5l-7 7 7 7', t('gallery.prev', 'Previous photo'));
    const next = navBtn('next', 'M9 5l7 7-7 7', t('gallery.next', 'Next photo'));
    frame.append(prev, next);

    // Filenames are not titles — no caption text, just the position.
    const cap = el('div', 'pg__cap');
    const count = el('p', 'pg__count mono');

    const dots = el('div', 'pg__dots');
    dots.setAttribute('role', 'tablist');
    dots.setAttribute('aria-label', 'Photos');

    // The position leads the row: the assistant's launcher floats over the
    // far corner of the page, and must never sit on the number.
    cap.append(count, dots);

    stage.setAttribute('role', 'group');
    stage.setAttribute('aria-roledescription', 'carousel');
    stage.append(frame, cap);
    host.appendChild(stage);

    host._refs = { count, dots, prev, next, frame };

    prev.addEventListener('click', () => go(idx - 1));
    next.addEventListener('click', () => go(idx + 1));

    buildDots();
    wireGestures(frame);
    show(0, true);
  }

  function el(tag, cls) {
    const n = document.createElement(tag);
    if (cls) n.className = cls;
    return n;
  }

  function navBtn(dir, path, label) {
    const b = el('button', `pg__nav pg__nav--${dir}`);
    b.type = 'button';
    b.setAttribute('aria-label', label);
    b.title = `${label} (${keyFor(dir)})`;
    b.setAttribute('aria-keyshortcuts', keyFor(dir) === '→' ? 'ArrowRight' : 'ArrowLeft');
    b.innerHTML =
      `<svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor"
            stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
         <path d="${path}"/></svg>`;
    return b;
  }

  function buildDots() {
    const { dots } = host._refs;
    dots.replaceChildren();
    // Too many dots becomes noise; past ~14 photos show a progress bar instead.
    if (items.length > 14) {
      dots.classList.add('pg__dots--bar');
      const bar = el('span', 'pg__bar');
      const fill = el('span', 'pg__bar-fill');
      bar.appendChild(fill);
      dots.appendChild(bar);
      return;
    }
    dots.classList.remove('pg__dots--bar');
    items.forEach((_, i) => {
      const d = el('button', 'pg__dot');
      d.type = 'button';
      d.setAttribute('role', 'tab');
      d.setAttribute('aria-label', `Photo ${i + 1}`);
      d.addEventListener('click', () => go(i));
      dots.appendChild(d);
    });
  }

  /* ── Crossfade ──────────────────────────────────────────── */
  function show(i, immediate = false) {
    const item = items[i];
    if (!item) return;

    const incoming = layers[1 - front];
    const outgoing = layers[front];
    const img = incoming.querySelector('img');

    // A cached image fires BOTH `complete` and `onload`, so this must run
    // at most once — swapping twice flips the layers back and wedges the
    // gallery on whichever photo was showing.
    let swapped = false;
    const swap = () => {
      if (swapped) return;
      swapped = true;
      clearTimeout(guard);
      incoming.classList.add('is-front');
      outgoing.classList.remove('is-front');
      front = 1 - front;
      busy = false;
    };

    img.alt = item.alt || '';

    if (immediate) {
      img.src = item.src;
      const back = outgoing.querySelector('img');
      back.src = item.src;
      back.alt = item.alt || '';
      busy = false;
      return void afterShow(i);
    }

    busy = true;
    // Never let a slow or dead image lock navigation.
    const guard = setTimeout(swap, 2500);

    // Swap as soon as the image is decoded. Deliberately NOT inside
    // requestAnimationFrame: rAF is paused in background tabs, which would
    // leave the gallery frozen until a visitor returns to it. The incoming
    // layer is already at opacity 0, so the CSS transition runs correctly
    // from a plain class change.
    img.onload = swap;
    img.onerror = swap;
    img.src = item.src;
    // Cached images may already be decoded and fire no load event.
    if (img.complete && img.naturalWidth) swap();

    afterShow(i);
  }

  function afterShow(i) {
    syncMeta(i);
    preload(i);
  }

  function syncMeta(i) {
    const { count, dots } = host._refs;
    count.textContent = `${i + 1} / ${items.length}`;

    if (dots.classList.contains('pg__dots--bar')) {
      const fill = dots.querySelector('.pg__bar-fill');
      if (fill) fill.style.transform = `scaleX(${(i + 1) / items.length})`;
      return;
    }
    [...dots.children].forEach((d, n) => {
      const on = n === i;
      d.classList.toggle('is-on', on);
      d.setAttribute('aria-selected', String(on));
    });
  }

  /** Keep the neighbours warm so next/prev is instant. */
  function preload(i) {
    [i + 1, i - 1].forEach((n) => {
      const it = items[(n + items.length) % items.length];
      if (it) { const p = new Image(); p.src = it.src; }
    });
  }

  /** The arrow key that means "next" or "previous" — it follows the layout,
   *  so on the Arabic page (where the arrows are mirrored) it is mirrored too. */
  function keyFor(dir) {
    const rtl = document.documentElement.dir === 'rtl';
    return (dir === 'next') !== rtl ? '→' : '←';
  }

  function go(i) {
    if (busy || !items.length) return;
    idx = ((i % items.length) + items.length) % items.length;
    show(idx);
  }

  /* ── Gestures & keyboard ────────────────────────────────── */
  function wireGestures(frame) {
    let x0 = null, y0 = null;
    frame.addEventListener('touchstart', (e) => {
      x0 = e.touches[0].clientX; y0 = e.touches[0].clientY;
    }, { passive: true });
    frame.addEventListener('touchend', (e) => {
      if (x0 === null) return;
      const dx = e.changedTouches[0].clientX - x0;
      const dy = e.changedTouches[0].clientY - y0;
      if (Math.abs(dx) > 50 && Math.abs(dx) > Math.abs(dy) * 1.5) go(idx + (dx < 0 ? 1 : -1));
      x0 = y0 = null;
    }, { passive: true });

    // Focusable, so a keyboard visitor can tab to it and see where they are.
    frame.tabIndex = 0;
  }

  /** ← and → flip the photos whenever the gallery is on screen — no need to
   *  click into it first. Left and right do nothing else on this page, so
   *  nothing is lost; the keys are still left alone wherever they already
   *  mean something (fields, the chat panel, the certificate viewer, the
   *  phone menu) and when the gallery is not what the visitor is looking at. */
  function onKey(e) {
    if (e.defaultPrevented || e.altKey || e.ctrlKey || e.metaKey || e.shiftKey) return;
    if (e.key !== 'ArrowLeft' && e.key !== 'ArrowRight') return;
    if (!items.length || !host._refs) return;

    const target = e.target instanceof Element ? e.target : null;
    if (target && target.closest(
      'input, textarea, select, [contenteditable=""], [contenteditable="true"], [role="slider"], .bot, #gal, .lb'
    )) return;
    const viewer = document.getElementById('gal');
    if (viewer && !viewer.hidden) return;
    const menu = document.getElementById('nav-links');
    if (menu && menu.classList.contains('is-open')) return;

    // Only while at least half of the plate is on screen.
    const r = host._refs.frame.getBoundingClientRect();
    const seen = Math.min(r.bottom, window.innerHeight) - Math.max(r.top, 0);
    if (seen < Math.min(r.height, window.innerHeight) * 0.5) return;

    e.preventDefault();
    const rtl = document.documentElement.dir === 'rtl';
    const forward = (e.key === 'ArrowRight') !== rtl;
    go(idx + (forward ? 1 : -1));
  }
  document.addEventListener('keydown', onKey);

  /* ── Load ───────────────────────────────────────────────── */
  async function load() {
    try {
      const res = await fetch('data/photo-gallery.json', { cache: 'no-cache' });
      if (!res.ok) throw new Error('no gallery data');
      const data = await res.json();
      items = Array.isArray(data.images) ? data.images : [];
      if (!items.length) throw new Error('empty');
      mount();
    } catch (_) {
      const p = document.createElement('p');
      p.className = 'lead';
      p.textContent = t('gallery.empty', 'The gallery is empty right now.');
      host.replaceChildren(p);
    }
    clearInterval(timer);
  }

  document.addEventListener('site:lang', () => {
    if (!items.length || !host._refs) return;
    syncMeta(idx);
    const { prev, next } = host._refs;
    const label = (btn, dir, key, fb) => {
      const text = t(key, fb);
      btn.setAttribute('aria-label', text);
      btn.title = `${text} (${keyFor(dir)})`;
      btn.setAttribute('aria-keyshortcuts', keyFor(dir) === '→' ? 'ArrowRight' : 'ArrowLeft');
    };
    label(prev, 'prev', 'gallery.prev', 'Previous photo');
    label(next, 'next', 'gallery.next', 'Next photo');
  });

  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', load);
  else load();
})();
